export const GET_SYNC_STATUS = "GET_SYNC_STATUS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_DETAILED_PRODUCT = "SET_DETAILED_PRODUCT";
export const COMPLETE_COMMIT_PRICE_CHANGE = "COMPLETE_COMMIT_PRICE_CHANGE";
export const SET_PRODUCTS_REQUESTED = "SET_PRODUCTS_REQUESTED";
export const GET_ORDERS = "GET_ORDERS";
export const COMPLETE_UPDATE_INVENTORY = "COMPLETE_UPDATE_INVENTORY";
